<?php
$anneeVisionne=2023;
$moisVisionne=02;
$nbrJoursMois=cal_days_in_month(CAL_GREGORIAN, $moisVisionne, $anneeVisionne);
$listeFermeturesDuMois=FermeturesManager::getList(null, ["dateFermeture"=>$anneeVisionne."-".$moisVisionne."-%"]);

echo '<main>';
echo '<div class="cote"></div>';
echo '<div class="mainGrid grid-col2-reduct">';
echo '    <!--Séparation Prestations/Pointages => Zone Prestations -->';
echo '    <div class="grid-presta tabCol grid-5-reduct pointHead bgc4">';
echo '        <div class="grid-columns-span-2 fullLine grid-lineSimple cellRight">';
echo '            <div></div>';
echo '            <div class="vMini">';
echo '                <div class="center" id="btnMasque">';
echo '                    <i class="fas fa-expand rotate-45 center"></i>';
echo '                </div>';
echo '            </div>';
echo '            <div></div>';
echo '        </div>';
echo '        <div class="center grid-lineDoublegrid-lineSimple cellBottom cellTop"></div>';
echo '        <div class="center grid-lineDouble cellBottom cellTop">Code Prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom cellTop colCachable noDisplay">UO de MAD<br />interne</div>';
echo '        <div class="center grid-lineDouble cellBottom cellTop colCachable noDisplay">Code Motif</div>';
echo '        <div class="center grid-lineDouble cellBottom cellTop colCachable noDisplay">Code Projet</div>';

echo '        <!------------------>';
echo '        <!------------------>';
echo '        <!------------------>';

echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">';
echo '            <div class="noDisplay colCachable"></div>';
echo '            <div class="triple">Jours ouvrés</div>';
echo '            <div class="noDisplay colCachable"></div>';
echo '        </div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">';
echo '            <div class="noDisplay colCachable"></div>';
echo '            <div class="triple">Nb jours absences (congés, maladie ...)&nbsp;<small id="info">ne pas saisir les absences RTT</small></div>';
echo '            <div class="noDisplay colCachable"></div>';
echo '        </div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">';
echo '            <div class="noDisplay colCachable"></div>';
echo '            <div class="triple">Jours ouvrés hors absences</div>';
echo '            <div class="noDisplay colCachable"></div>';
echo '        </div>';
echo '    </div>';
echo '    <!--Séparation Prestations/Pointages => Zone Pointages -->';
echo '    <div class="grid-pointage tabCol pointHead">';
echo '        <div class="center grid-lineSimple cellBottom bgc4">Contrôle</div>';
echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
echo '        <div class="grid-lineSimple cellBottom"></div>';
for ($jour=1; $jour <= $nbrJoursMois; $jour++) {
    $jourActu=mktime(0,0,0,$moisVisionne,$jour,$anneeVisionne);
    if(getdate($jourActu)['wday']==0||getdate($jourActu)['wday']==6){
        $jourOuvert="";
    }else{
        $jourOuvert="OK";
    }
    echo '        <div class="center grid-lineSimple cellBottom">'.$jourOuvert.'</div>';
}
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellOK grid-lineSimple cellBottom">OK</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';
// echo '        <div class="center cellKO grid-lineSimple cellBottom">KO</div>';

echo '        <!-- Lignes 9 et 10 -->';
echo '        <div class="cellBottom center grid-lineDouble bgc4">Total</div>';
echo '        <div class="cellBottom center grid-lineDouble bgc4">%GTA</div>';
echo '        <div class="cellBottom grid-lineDouble bgc4"></div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">1<br />Dim</div>';
echo '        <div class="center grid-lineDouble cellBottom work">2<br />Lun</div>';
echo '        <div class="center grid-lineDouble cellBottom work">3<br />Mar</div>';
echo '        <div class="center grid-lineDouble cellBottom work">4<br />Mer</div>';
echo '        <div class="center grid-lineDouble cellBottom work">5<br />Jeu</div>';
echo '        <div class="center grid-lineDouble cellBottom work">6<br />Ven</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">7<br />Sam</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">8<br />Dim</div>';
echo '        <div class="center grid-lineDouble cellBottom work">9<br />Lun</div>';
echo '        <div class="center grid-lineDouble cellBottom work">10<br />Mar</div>';
echo '        <div class="center grid-lineDouble cellBottom work">11<br />Mer</div>';
echo '        <div class="center grid-lineDouble cellBottom work">12<br />Jeu</div>';
echo '        <div class="center grid-lineDouble cellBottom work">13<br />Ven</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">14<br />Sam</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">15<br />Dim</div>';
echo '        <div class="center grid-lineDouble cellBottom work">16<br />Lun</div>';
echo '        <div class="center grid-lineDouble cellBottom work">17<br />Mar</div>';
echo '        <div class="center grid-lineDouble cellBottom work">18<br />Mer</div>';
echo '        <div class="center grid-lineDouble cellBottom work">19<br />Jeu</div>';
echo '        <div class="center grid-lineDouble cellBottom work">20<br />Ven</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">21<br />Sam</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">22<br />Dim</div>';
echo '        <div class="center grid-lineDouble cellBottom work">23<br />Lun</div>';
echo '        <div class="center grid-lineDouble cellBottom work">24<br />Mar</div>';
echo '        <div class="center grid-lineDouble cellBottom work">25<br />Mer</div>';
echo '        <div class="center grid-lineDouble cellBottom work">26<br />Jeu</div>';
echo '        <div class="center grid-lineDouble cellBottom work">27<br />Ven</div>';
echo '        <div class="center grid-lineDouble cellBottom noWork">28<br />Sam</div>';
// echo '        <div class="center grid-lineDouble cellBottom noWork">29<br />Dim</div>';
// echo '        <div class="center grid-lineDouble cellBottom work">30<br />Lun</div>';
// echo '        <div class="center grid-lineDouble cellBottom work">31<br />Mar</div>';
echo '        <!-- Ligne 11 -->';
echo '        <div class="cellBottom center grid-lineSimple bgc4">22</div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
// echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
// echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
// echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <!-- Ligne 12 -->';
echo '        <div class="cellBottom center grid-lineSimple bgc4">0</div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
// echo '        <div class="cellBottom center noWork grid-lineSimple"></div>';
// echo '        <div class="cellBottom center work grid-lineSimple"></div>';
// echo '        <div class="cellBottom center work grid-lineSimple"></div>';
echo '        <!-- Ligne 13 -->';
echo '        <div class="cellBottom center grid-lineSimple bgc4">22</div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom grid-lineSimple bgc4"></div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
// echo '        <div class="cellBottom center noWork grid-lineSimple">0,0</div>';
// echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';
// echo '        <div class="cellBottom center work grid-lineSimple">1,0</div>';        
echo '    </div>';
echo '    <div class="grid-presta tabCol grid-5-reduct pointMove">';

echo '        <!--------------------------->';
echo '        <!-- Prestations de type 1 -->';
echo '        <!--------------------------->';
echo '        <!-- Titre -->';
echo '        <div class="center grid-columns-span-2 fullLine grid-lineSimple cellBottom left">1 - Activité de production (y compris présentation titres CCxx)</div>';
echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';

echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';

echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">Option pour ajouter une ligne</div>';

echo '        <!--------------------------->';
echo '        <!-- Prestations de type 2 -->';
echo '        <!--------------------------->';
echo '        <!-- Titre -->';
echo '        <div class="center grid-columns-span-2 fullLine grid-lineSimple cellBottom left">2 - Missions Nationales de Service Public</div>';
echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">Option pour ajouter une ligne</div>';

echo '        <!--------------------------->';
echo '        <!-- Prestations de type 3 -->';
echo '        <!--------------------------->';
echo '        <!-- Titre -->';
echo '        <div class="center grid-columns-span-2 fullLine grid-lineSimple cellBottom left">3 - Perfectionnement</div>';
echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">Option pour ajouter une ligne</div>';
echo '        <!--------------------------->';
echo '        <!-- Prestations de type 4 -->';
echo '        <!--------------------------->';
echo '        <!-- Titre -->';
echo '        <div class="center grid-columns-span-2 fullLine grid-lineSimple cellBottom left">4 - Mandat</div>';
echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">Option pour ajouter une ligne</div>';
echo '        <!--------------------------->';
echo '        <!-- Prestations de type 5 -->';
echo '        <!--------------------------->';
echo '        <!-- Titre -->';
echo '        <div class="center grid-columns-span-2 fullLine grid-lineSimple cellBottom left">5 - Autres activités de support</div>';
echo '        <!-- Ligne -->';
echo '        <div class="center grid-lineDouble cellBottom">Combobox des prestations possibles</div>';
echo '        <div class="center grid-lineDouble cellBottom">Code de la prestation</div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable notApplicable noDisplay"></div>';
echo '        <div class="center grid-lineDouble cellBottom colCachable work noDisplay"></div>';
echo '        <div class="grid-columns-span-2 fullLine center grid-lineSimple cellBottom">Option pour ajouter une ligne</div>';
echo '    </div>';
echo '    <div class="grid-pointage tabCol pointMove">';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';

echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';

echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';

echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';

echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';

echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';

echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';

echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,00</div>';
echo '        <div class="cellBottom center grid-lineDouble">0,0%</div>';
echo '        <div class="cellBottom grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center noWork grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="cellBottom center work grid-lineDouble"></div>';
echo '        <div class="grid-columns-span-34 grid-lineSimple cellBottom">&nbsp;</div>';
echo '    </div>';
echo '</div>';
echo '<div class="cote"></div></main>';