
INSERT INTO gta_textes (`idTexte`, `codeTexte`, `fr`, `en`) VALUES
(1, 'Bonjour', 'Bonjour', 'Hello'),
(2, 'Connexion', 'Connexion', 'Log in'),
(3, 'Deconnexion', 'Deconnexion', 'Log out'),
(4, 'Accueil', 'Accueil', 'Home'),
(5, 'AdresseEmail', 'Adresse email', 'Email address'),
(6, 'Mdp', 'Mot de passe', 'Password'),
(7, 'Inscription', 'Inscription', 'Registration'),
(8, 'Nom', 'Nom', 'Surname'),
(9, 'Prenom', 'Prenom', 'Name'),
(10, 'InfoMdpLegend', 'Veuillez saisir au moins', 'Please enter at least'),
(11, 'UneMajuscule', '1 majuscule', '1 uppercase'),
(12, 'UneMinuscule', '1 minuscule', '1 lowercase'),
(13, 'UnChiffre', '1 chiffre', '1 number'),
(14, 'UnCaractereSpecial', '1 caractère spécial ( ! @ & # * ^ $ % +)', '1 special character ( ! @ & # * ^ $ % +)'),
(15, 'MinimumCaractere', '8 caractères', '8 character'),
(16, 'Confirmation', 'Confirmation', 'Confirmation'),
(17, 'Reset', 'Réinitialisation', 'Reset'),
(18, 'inputDefault', 'Choisir une valeur', 'Choose a value'),
(19, 'Envoyer', 'Envoyer', 'Send'),
(20, 'Bonjour', 'Bonjour', 'Hello'),
(21, 'Connexion', 'Connexion', 'Log in'),
(22, 'Deconnexion', 'Deconnexion', 'Log out'),
(23, 'Accueil', 'Accueil', 'Home'),
(24, 'AdresseEmail', 'Adresse email', 'Email address'),
(25, 'Mdp', 'Mot de passe', 'Password'),
(26, 'Inscription', 'Inscription', 'Registration'),
(27, 'Nom', 'Nom', 'Surname'),
(28, 'Prenom', 'Prenom', 'Name'),
(29, 'InfoMdpLegend', 'Veuillez saisir au moins', 'Please enter at least'),
(30, 'UneMajuscule', '1 majuscule', '1 uppercase'),
(31, 'UneMinuscule', '1 minuscule', '1 lowercase'),
(32, 'UnChiffre', '1 chiffre', '1 number'),
(33, 'UnCaractereSpecial', '1 caractère spécial ( ! @ & # * ^ $ % +)', '1 special character ( ! @ & # * ^ $ % +)'),
(34, 'MinimumCaractere', '8 caractères', '8 character'),
(35, 'Confirmation', 'Confirmation', 'Confirmation'),
(36, 'Reset', 'Réinitialisation', 'Reset'),
(37, 'inputDefault', 'Choisir une valeur', 'Choose a value'),
(38, 'Envoyer', 'Envoyer', 'Send'),
(39, 'Bonjour', 'Bonjour', 'Hello'),
(40, 'Connexion', 'Connexion', 'Log in'),
(41, 'Deconnexion', 'Deconnexion', 'Log out'),
(42, 'Accueil', 'Accueil', 'Home'),
(43, 'AdresseEmail', 'Adresse email', 'Email address'),
(44, 'Mdp', 'Mot de passe', 'Password'),
(45, 'Inscription', 'Inscription', 'Registration'),
(46, 'Nom', 'Nom', 'Surname'),
(47, 'Prenom', 'Prenom', 'Name'),
(48, 'InfoMdpLegend', 'Veuillez saisir au moins', 'Please enter at least'),
(49, 'UneMajuscule', '1 majuscule', '1 uppercase'),
(50, 'UneMinuscule', '1 minuscule', '1 lowercase'),
(51, 'UnChiffre', '1 chiffre', '1 number'),
(52, 'UnCaractereSpecial', '1 caractère spécial ( ! @ & # * ^ $ % +)', '1 special character ( ! @ & # * ^ $ % +)'),
(53, 'MinimumCaractere', '8 caractères', '8 character'),
(54, 'Confirmation', 'Confirmation', 'Confirmation'),
(55, 'Reset', 'Réinitialisation', 'Reset'),
(56, 'inputDefault', 'Choisir une valeur', 'Choose a value'),
(57, 'Envoyer', 'Envoyer', 'Send'),
(58, 'Bonjour', 'Bonjour', 'Hello'),
(59, 'Connexion', 'Connexion', 'Log in'),
(60, 'Deconnexion', 'Deconnexion', 'Log out'),
(61, 'Accueil', 'Accueil', 'Home'),
(62, 'AdresseEmail', 'Adresse email', 'Email address'),
(63, 'Mdp', 'Mot de passe', 'Password'),
(64, 'Inscription', 'Inscription', 'Registration'),
(65, 'Nom', 'Nom', 'Surname'),
(66, 'Prenom', 'Prenom', 'Name'),
(67, 'InfoMdpLegend', 'Veuillez saisir au moins', 'Please enter at least'),
(68, 'UneMajuscule', '1 majuscule', '1 uppercase'),
(69, 'UneMinuscule', '1 minuscule', '1 lowercase'),
(70, 'UnChiffre', '1 chiffre', '1 number'),
(71, 'UnCaractereSpecial', '1 caractère spécial ( ! @ & # * ^ $ % +)', '1 special character ( ! @ & # * ^ $ % +)'),
(72, 'MinimumCaractere', '8 caractères', '8 character'),
(73, 'Confirmation', 'Confirmation', 'Confirmation'),
(74, 'Reset', 'Réinitialisation', 'Reset'),
(75, 'inputDefault', 'Choisir une valeur', 'Choose a value'),
(76, 'Envoyer', 'Envoyer', 'Send'),
(77, 'Bonjour', 'Bonjour', 'Hello'),
(78, 'Connexion', 'Connexion', 'Log in'),
(79, 'Deconnexion', 'Deconnexion', 'Log out'),
(80, 'Accueil', 'Accueil', 'Home'),
(81, 'AdresseEmail', 'Adresse email', 'Email address'),
(82, 'Mdp', 'Mot de passe', 'Password'),
(83, 'Inscription', 'Inscription', 'Registration'),
(84, 'Nom', 'Nom', 'Surname'),
(85, 'Prenom', 'Prenom', 'Name'),
(86, 'InfoMdpLegend', 'Veuillez saisir au moins', 'Please enter at least'),
(87, 'UneMajuscule', '1 majuscule', '1 uppercase'),
(88, 'UneMinuscule', '1 minuscule', '1 lowercase'),
(89, 'UnChiffre', '1 chiffre', '1 number'),
(90, 'UnCaractereSpecial', '1 caractère spécial ( ! @ & # * ^ $ % +)', '1 special character ( ! @ & # * ^ $ % +)'),
(91, 'MinimumCaractere', '8 caractères', '8 character'),
(92, 'Confirmation', 'Confirmation', 'Confirmation'),
(93, 'Reset', 'Réinitialisation', 'Reset'),
(94, 'inputDefault', 'Choisir une valeur', 'Choose a value'),
(95, 'Envoyer', 'Envoyer', 'Send');