
CREATE TABLE gta_Entites ( 
   idEntite INT NOT NULL AUTO_INCREMENT PRIMARY KEY , 
   libelleEntite VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

INSERT INTO gta_Entites (IdEntite, LibelleEntite) VALUES (1, 'Calais-Dunkerque');

ALTER TABLE gta_Activites ADD idEntite INT NULL DEFAULT 1 AFTER idActivite;
ALTER TABLE gta_Activites ADD CONSTRAINT FK_Activite_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_ActivitesParTypes ADD idEntite INT NULL DEFAULT 1 AFTER idActivitesParTypes;
ALTER TABLE gta_ActivitesParTypes ADD CONSTRAINT FK_ActiviteParType_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Associations ADD idEntite INT NULL DEFAULT 1 AFTER idAssociation;
ALTER TABLE gta_Associations ADD CONSTRAINT FK_Association_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Centres ADD idEntite INT NULL DEFAULT 1 AFTER idCentre;
ALTER TABLE gta_Centres ADD CONSTRAINT FK_Centres_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Contrats ADD idEntite INT NULL DEFAULT 1 AFTER idContrat;
ALTER TABLE gta_Contrats ADD CONSTRAINT FK_Contrats_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Fermetures ADD idEntite INT NULL DEFAULT 1 AFTER idFermeture;
ALTER TABLE gta_Fermetures ADD CONSTRAINT FK_Fermetures_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Logs ADD idEntite INT NULL DEFAULT 1 AFTER idLog;
ALTER TABLE gta_Logs ADD CONSTRAINT FK_Logs_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Motifs ADD idEntite INT NULL DEFAULT 1 AFTER idMotif;
ALTER TABLE gta_Motifs ADD CONSTRAINT FK_Motifs_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Pointages ADD idEntite INT NULL DEFAULT 1 AFTER idPointage;
ALTER TABLE gta_Pointages ADD CONSTRAINT FK_Pointages_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Preferences ADD idEntite INT NULL DEFAULT 1 AFTER idPreference;
ALTER TABLE gta_Preferences ADD CONSTRAINT FK_Preferences_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Prestations ADD idEntite INT NULL DEFAULT 1 AFTER idPrestation;
ALTER TABLE gta_Prestations ADD CONSTRAINT FK_Prestations_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Projets ADD idEntite INT NULL DEFAULT 1 AFTER idProjet;
ALTER TABLE gta_Projets ADD CONSTRAINT FK_Projets_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_TypePrestations ADD idEntite INT NULL DEFAULT 1 AFTER idTypePrestation;
ALTER TABLE gta_TypePrestations ADD CONSTRAINT FK_TypesPrestations_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gta_Uos ADD idEntite INT NULL DEFAULT 1 AFTER idUo;
ALTER TABLE gta_Uos ADD CONSTRAINT FK_Uos_Entite FOREIGN KEY (idEntite) REFERENCES gta_Entites(IdEntite) ON DELETE RESTRICT ON UPDATE RESTRICT;
